# files
Files:
  my_project:
    settings:
      __init__.py: file
      dev.py: file
      prof.py: file
    mainapp:
      __init__.py: file
      models.py: file
      views.py: file
      templates:
        mainapp:
          base.html: file
          index.html: file
    authapp:
      __init__.py: file
      models.py: file
      views.py: file
      templates:
        authapp:
          base.html: file
          index.html: file